# Generated by Django 3.0.6 on 2020-06-04 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='活動名稱')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classname', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.TextField(max_length=10)),
                ('authority', models.TextField(max_length=1)),
                ('position', models.TextField(max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to='app1.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idea_title', models.CharField(max_length=20, null=True, verbose_name='點子標題')),
                ('no', models.CharField(max_length=7, verbose_name='No')),
                ('sub_title', models.CharField(max_length=20, null=True, verbose_name='標題')),
                ('author', models.CharField(max_length=10, null=True, verbose_name='作者簽名')),
                ('sketch', models.ImageField(upload_to='cards/image/')),
                ('description', models.TextField(null=True, verbose_name='描述')),
                ('feature', models.TextField(null=True, verbose_name='特點')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='app1.Activity')),
                ('group', models.ManyToManyField(related_name='card', to='app1.Group')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='app1.Classroom'),
        ),
        migrations.AddField(
            model_name='activity',
            name='group',
            field=models.ManyToManyField(related_name='activity', to='app1.Group'),
        ),
    ]
